import CardForm from '../../components/CardForm'
import Head from 'next/head'
import Tabs from '../../components/Tabs'
import LoginForm from '../../components/forms/LoginForm'
import SingUpForm from '../../components/forms/SingUpForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="hero is-fullheight">
          <div className="hero-body">
            <div className="container">
              {/* <CardForm /> */}
              <Tabs>
                <LoginForm />
                <SingUpForm />
              </Tabs>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}