import Head from 'next/head'
import CardForm from '../../components/CardForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <section className="hero is-fullheight">
        <div className="hero-body">
          <div className="container">
            <CardForm />
          </div>
        </div>
      </section>
      </main>
    </>
  )
}
